=== ivaannts/pokedex/pokedex.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="pokedex">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pokemon" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numero" type="xs:integer"/>
                            <xs:element name="imagen" type="xs:string"/>
                            <xs:element name="imagen_shiny" type="xs:string"/>
                            <xs:element name="puntos_base">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ps" type="xs:integer"/>
                                        <xs:element name="ataque" type="xs:integer"/>
                                        <xs:element name="defensa" type="xs:integer"/>
                                        <xs:element name="ataque_especial" type="xs:integer"/>
                                        <xs:element name="defensa_especial" type="xs:integer"/>
                                        <xs:element name="velocidad" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="altura" type="xs:float"/>
                            <xs:element name="peso" type="xs:float"/>
                            <xs:element name="genero">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Masculino|Femenino"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="categoria" type="xs:string"/>
                            <xs:element name="habilidad" maxOccurs = "unbounded" type="xs:string"/>
                            <xs:element name="tipo" maxOccurs="2">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Planta"/>
                                        <xs:enumeration value="Fuego"/>
                                        <xs:enumeration value="Agua"/>
                                        <xs:enumeration value="Normal"/>
                                        <xs:enumeration value="Volador"/>
                                        <xs:enumeration value="Hielo"/>
                                        <xs:enumeration value="Eléctrico"/>
                                        <xs:enumeration value="Roca"/>
                                        <xs:enumeration value="Tierra"/>
                                        <xs:enumeration value="Veneno"/>
                                        <xs:enumeration value="Psíquico"/>
                                        <xs:enumeration value="Siniestro"/>
                                        <xs:enumeration value="Dragón"/>
                                        <xs:enumeration value="Hada"/>
                                        <xs:enumeration value="Lucha"/>
                                        <xs:enumeration value="Fantasma"/>
                                        <xs:enumeration value="Acero"/>
                                        <xs:enumeration value="Bicho"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="debilidad" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Planta"/>
                                        <xs:enumeration value="Fuego"/>
                                        <xs:enumeration value="Agua"/>
                                        <xs:enumeration value="Normal"/>
                                        <xs:enumeration value="Volador"/>
                                        <xs:enumeration value="Hielo"/>
                                        <xs:enumeration value="Eléctrico"/>
                                        <xs:enumeration value="Roca"/>
                                        <xs:enumeration value="Tierra"/>
                                        <xs:enumeration value="Veneno"/>
                                        <xs:enumeration value="Psíquico"/>
                                        <xs:enumeration value="Siniestro"/>
                                        <xs:enumeration value="Dragón"/>
                                        <xs:enumeration value="Hada"/>
                                        <xs:enumeration value="Lucha"/>
                                        <xs:enumeration value="Fantasma"/>
                                        <xs:enumeration value="Acero"/>
                                        <xs:enumeration value="Bicho"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="evolucion" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                    <xs:attribute name="nivel" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ivaannts/pokedex/pokedex.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/pokedex.xsl"?>
<pokedex xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xsi:noNamespaceSchemaLocation='../xsd/pokedex.xsd'>
    <pokemon>
        <numero>1</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/1_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>45</ps>
            <ataque>49</ataque>
            <defensa>49</defensa>
            <ataque_especial>65</ataque_especial>
            <defensa_especial>65</defensa_especial>
            <velocidad>45</velocidad>
        </puntos_base>
        <nombre>Bulbasaur</nombre>
        <descripcion>A esta planta en su espalda, le brota un retoño grande. Luego crece un capullo todavía más
            grande.
        </descripcion>
        <altura>0.7</altura>
        <peso>6.9</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Semilla</categoria>
        <habilidad>Espesura</habilidad>
        <tipo>Planta</tipo>
        <tipo>Veneno</tipo>
        <debilidad>Fuego</debilidad>
        <debilidad>Volador</debilidad>
        <debilidad>Psíquico</debilidad>
        <debilidad>Hielo</debilidad>
        <evolucion nombre="Ivysaur" nivel="16"/>
    </pokemon>
    <pokemon>
        <numero>2</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/002.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/2_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>60</ps>
            <ataque>62</ataque>
            <defensa>63</defensa>
            <ataque_especial>80</ataque_especial>
            <defensa_especial>80</defensa_especial>
            <velocidad>60</velocidad>
        </puntos_base>
        <nombre>Ivysaur</nombre>
        <descripcion>Si le da el sol, la flor en su espalda crece rápidamente. Su aroma atrae a gente que está a su
            alrededor.
        </descripcion>
        <altura>1.0</altura>
        <peso>13.0</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Semilla</categoria>
        <habilidad>Espesura</habilidad>
        <tipo>Planta</tipo>
        <tipo>Veneno</tipo>
        <debilidad>Fuego</debilidad>
        <debilidad>Volador</debilidad>
        <debilidad>Psíquico</debilidad>
        <debilidad>Hielo</debilidad>
        <evolucion nombre="Venusaur" nivel="32"/>
    </pokemon>
    <pokemon>
        <numero>3</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/003.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/3_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>80</ps>
            <ataque>82</ataque>
            <defensa>83</defensa>
            <ataque_especial>100</ataque_especial>
            <defensa_especial>100</defensa_especial>
            <velocidad>80</velocidad>
        </puntos_base>
        <nombre>Venusaur</nombre>
        <descripcion>Hay una flor enorme en la espalda de Venusaur. La flor lanza una gran cantidad de polen cuando
            florece.
        </descripcion>
        <altura>2.0</altura>
        <peso>100.0</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Semilla</categoria>
        <habilidad>Espesura</habilidad>
        <tipo>Planta</tipo>
        <tipo>Veneno</tipo>
        <debilidad>Fuego</debilidad>
        <debilidad>Volador</debilidad>
        <debilidad>Psíquico</debilidad>
        <debilidad>Hielo</debilidad>
    </pokemon>
    <pokemon>
        <numero>4</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/4_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>39</ps>
            <ataque>52</ataque>
            <defensa>43</defensa>
            <ataque_especial>60</ataque_especial>
            <defensa_especial>50</defensa_especial>
            <velocidad>65</velocidad>
        </puntos_base>
        <nombre>Charmander</nombre>
        <descripcion>La llama que tiene en la punta de la cola arde con fuerza en función de sus sentimientos. Oscila
            cuando está contento y se debilita cuando está triste.
        </descripcion>
        <altura>0.6</altura>
        <peso>8.5</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Lagartija</categoria>
        <habilidad>Mar Llamas</habilidad>
        <tipo>Fuego</tipo>
        <debilidad>Tierra</debilidad>
        <debilidad>Roca</debilidad>
        <debilidad>Agua</debilidad>
        <evolucion nombre="Charmaleon" nivel="16"/>
    </pokemon>
    <pokemon>
        <numero>5</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/005.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/5_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>58</ps>
            <ataque>64</ataque>
            <defensa>58</defensa>
            <ataque_especial>80</ataque_especial>
            <defensa_especial>65</defensa_especial>
            <velocidad>80</velocidad>
        </puntos_base>
        <nombre>Charmeleon</nombre>
        <descripcion>Charmeleon destruye a sus oponentes sin piedad con sus garras afiladas, aunque a veces se muestra
            bondadoso. Tras derrotar a un oponente fuerte, se vuelve un tanto presumido.
        </descripcion>
        <altura>1.1</altura>
        <peso>19.0</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Llama</categoria>
        <habilidad>Mar Llamas</habilidad>
        <tipo>Fuego</tipo>
        <debilidad>Tierra</debilidad>
        <debilidad>Roca</debilidad>
        <debilidad>Agua</debilidad>
        <evolucion nombre="Charizard" nivel="36"/>
    </pokemon>
    <pokemon>
        <numero>6</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/006.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/6_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>78</ps>
            <ataque>84</ataque>
            <defensa>78</defensa>
            <ataque_especial>109</ataque_especial>
            <defensa_especial>85</defensa_especial>
            <velocidad>100</velocidad>
        </puntos_base>
        <nombre>Charizard</nombre>
        <descripcion>Charizard vuela buscando oponentes poderosos. Su aliento de fuego es tan caliente que funde las
            rocas. Causa incendios forestales sin querer.
        </descripcion>
        <altura>1.7</altura>
        <peso>90.5</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Llama</categoria>
        <habilidad>Mar Llamas</habilidad>
        <tipo>Fuego</tipo>
        <tipo>Volador</tipo>
        <debilidad>Roca</debilidad>
        <debilidad>Agua</debilidad>
        <debilidad>Eléctrico</debilidad>
    </pokemon>
    <pokemon>
        <numero>7</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/007.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/7_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>44</ps>
            <ataque>48</ataque>
            <defensa>65</defensa>
            <ataque_especial>50</ataque_especial>
            <defensa_especial>64</defensa_especial>
            <velocidad>43</velocidad>
        </puntos_base>
        <nombre>Squirtle</nombre>
        <descripcion>El caparazón de Squirtle no le sirve solo de protección. La forma redondeada del caparazón y la
            superficie estriada le ayudan a minimizar la resistencia al agua y le permiten nadar a gran velocidad.
        </descripcion>
        <altura>0.5</altura>
        <peso>9.0</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Tortuguita</categoria>
        <habilidad>Torrente</habilidad>
        <tipo>Agua</tipo>
        <debilidad>Planta</debilidad>
        <debilidad>Eléctrico</debilidad>
        <evolucion nombre="Wartortle" nivel="16"/>
    </pokemon>
    <pokemon>
        <numero>8</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/008.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/8_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>59</ps>
            <ataque>63</ataque>
            <defensa>80</defensa>
            <ataque_especial>65</ataque_especial>
            <defensa_especial>80</defensa_especial>
            <velocidad>58</velocidad>
        </puntos_base>
        <nombre>Wartortle</nombre>
        <descripcion>Se dice que Wartortle vive 10.000 años. Es un Pokémon muy popular como símbolo de longevidad y
            buena suerte.
        </descripcion>
        <altura>1.0</altura>
        <peso>22.5</peso>
        <genero>Masculino</genero>
        <categoria>Pokémon Tortuga</categoria>
        <habilidad>Torrente</habilidad>
        <tipo>Agua</tipo>
        <debilidad>Planta</debilidad>
        <debilidad>Eléctrico</debilidad>
        <evolucion nombre="Blastoise" nivel="36"/>
    </pokemon>
    <pokemon>
        <numero>9</numero>
        <imagen>https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/009.png</imagen>
        <imagen_shiny>https://www.pokencyclopedia.info/sprites/gen1/normal/9_shiny.png</imagen_shiny>
        <puntos_base>
            <ps>79</ps>
            <ataque>83</ataque>
            <defensa>100</defensa>
            <ataque_especial>85</ataque_especial>
            <defensa_especial>105</defensa_especial>
            <velocidad>78</velocidad>
        </puntos_base>
        <nombre>Blastoise</nombre>
